device: cuda

model:
    id: my_model
    dendrite_pool:
      name: DummyDendritePool
      args:
        fail_rate: 0.1
        data_path: nq_open
    gating_model:
      name: HuggingFaceGatingModel
      args:
        model_name: EleutherAI/gpt-neo-125m
        tokenizer_name: EleutherAI/gpt-neo-125m
    reward_model:
      name: HuggingFaceRewardModel
      args:
        model_path: Dahoas/gpt2-rm-static
        tokenizer_path: EleutherAI/gpt-j-6b
    subtensor:
      name: DummySubtensor
      args:
        epoch_length: 10
        network: mirror-subtensor
    metagraph:
      name: DummyMetagraph
      args:
        netuid: 0
        network: mirror-metagraph
        num_nodes: 16
    alpha: 0.01

data:
    id: my_data
    path: nq_open
    schema:
      train:
        - row:
          question: question
          answer: answer
    sample:
      method: first
      n: 100

query:
    id: my_query
    chunk_size: 1
    method:
      # name: forward
      name: train
      args:
        max_iter: 10
    ignore_attr:
      - hotkeys
      - block

analysis:
    id: my_analysis
    requires:
      - my_query
    create_features:
      - question_length
      - num_words
      - avg_word_length
    plot:
      rewards:
        - question_length
        - num_words
        - avg_word_length
      scores:
        - question_length
        - num_words
        - avg_word_length